### PR TITLE
Created patch 2

### PR DESCRIPTION
**Pull request by what-does-that-do**
This patch contains the following bugfixes and improvements:
   - Built-in camera resolution can be changed.
   - USB cameras' resolution and focal lengths can be changed.
   - Vision section of docs updated to match with instructions.

Please would you check I've done this right?

Files changed: 
- `vision.html` (vision docs page)
- `vision.py`

### CODE REVIEW

**Comment by MostlyTurquoise** [comment]
This looks good, only one point though; In theory /built should be the directory containing built patches, and /built/patches shouldn't exist, also a built patch should not be committed (unless we need to i.e. so phoenix can access it where we might add it to a "deploy" subdirectory or similar). Will build and check the patch on my own brain probably this evening (unless you have already tested it on your brain), then it can be merged and released to teams.

**Comment by what-does-that-do** [comment]
Yeah that was my error, I passed `patches/<patch name>` in as the patch name, instead of just passing in `patch name`..

I don't have a brain at home at the moment so if you could test it that'd be great, check USB cams and resolution as in the sheep docs if you don't mind. The `robot.py` stuff is all tested, it's just never been tested as an actual patch.

**Comment by what-does-that-do** [comment]
Would you like me to delete the `/built` directory from this branch?

**Comment by MostlyTurquoise** [comment]
That would be good, thanks.

**Comment by what-does-that-do** [comment]
All done, have deleted the `built` directory.

**Review by MostlyTurquoise — APPROVED** [review]
Looks good to me! Feel free to merge at your leisure.

**Pull request merged**
